name: test
on:
  push:
    branches:
      - test

jobs:
  test:
    name: 'test job'
    runs-on: [self-hosted,r1]
    steps:
     - name: checkout
       uses: actions/checkout@v4
     - name: run
       run: echo "hello world
