name: Self-hosted Runner Workflow

on:
    push:
        branches:
            - test
jobs:
  self-hosted-job:
        runs-on: [self-hosted,r1]
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Run a sample script
            run: echo "Hello from self-hosted runner !"
