name: Simple Workflow on Self-hosted Runner

on:
  push:
    branches:
      - test

jobs:
  job1:
    runs-on: [self-hosted,r1]
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo "job1 is running on self-hosted runner 1"
  
  job2:
    needs: job1
    runs-on: [self-hosted,r1]
    steps:
      - uses: actions/checkout@v4
      - name: Run one-line script
        run: echo "job2 is running on self-hosted runner 1 after job1"
